"use client";
import dynamic from "next/dynamic";
import {AlertTriangle,BarChart3,Bell,ChevronDown,ClipboardList,Construction,Download,Filter,Landmark,Layers3,Map,MapPin,Menu,Plus,Search,Settings,ShipWheel,Signpost,TrafficCone,WalletCards,Wrench,X} from "lucide-react";
import {FormEvent,useEffect,useMemo,useState} from "react";
import type {MapItem} from "./map-view";
const MapView=dynamic(()=>import("./map-view"),{ssr:false,loading:()=> <div className="map-loading">Chargement de la carte…</div>});
type Incident=MapItem&{category:string;severity:"Critique"|"Élevée"|"Modérée"};
const seed:Incident[]=[
 {id:"FER-2841",category:"Voirie",title:"Nid-de-poule important",location:"Bd. VGE, Marcory",severity:"Critique",status:"À traiter",lat:5.295,lng:-3.984,color:"#d84b3e"},
 {id:"FER-2837",category:"Feux",title:"Feu tricolore hors service",location:"Carrefour Indénié",severity:"Élevée",status:"Équipe affectée",lat:5.348,lng:-4.006,color:"#ef8e34"},
 {id:"FER-2829",category:"Accotement",title:"Curage d’ouvrage requis",location:"A3, sortie Anyama",severity:"Modérée",status:"Planifié",lat:5.493,lng:-4.052,color:"#d6ad31"},
 {id:"FER-2818",category:"Bac",title:"Inspection du bac automoteur",location:"Jacqueville",severity:"Modérée",status:"Planifié",lat:5.205,lng:-4.416,color:"#28707a"},
 {id:"FER-2806",category:"Voirie",title:"Dégradation de chaussée",location:"Yamoussoukro, A6",severity:"Élevée",status:"Diagnostic",lat:6.821,lng:-5.274,color:"#ef8e34"},
 {id:"FER-2794",category:"Péage",title:"Inspection gare de péage",location:"Attinguié, Autoroute du Nord",severity:"Modérée",status:"Contrôle",lat:5.42,lng:-4.18,color:"#16786b"}
];
const nav=[["Vue d’ensemble",BarChart3],["Carte & réseau",Map],["Signalements",AlertTriangle],["Interventions",ClipboardList],["Financement",WalletCards],["Patrimoine",Signpost],["Ouvrages & bacs",ShipWheel]] as const;
export default function Home(){
 const [active,setActive]=useState("Vue d’ensemble"),[items,setItems]=useState(seed),[selected,setSelected]=useState<Incident|null>(seed[0]),[modal,setModal]=useState(false),[layers,setLayers]=useState(false),[query,setQuery]=useState(""),[formError,setFormError]=useState("");
 useEffect(()=>{fetch("/api/incidents").then(r=>r.ok?r.json():null).then(payload=>{if(!payload?.incidents?.length)return;const rows:Incident[]=payload.incidents.map((x:Record<string,string|number>)=>({id:String(x.reference),category:String(x.category),title:String(x.title),location:String(x.location),severity:String(x.severity) as Incident["severity"],status:String(x.status),lat:Number(x.latitude),lng:Number(x.longitude),color:x.severity==="Critique"?"#d84b3e":x.severity==="Élevée"?"#ef8e34":"#28707a"}));setItems(rows);setSelected(rows[0])}).catch(()=>{})},[]);
 const filtered=useMemo(()=>items.filter(x=>`${x.title} ${x.location} ${x.category}`.toLowerCase().includes(query.toLowerCase())),[items,query]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setFormError("");const d=new FormData(e.currentTarget);const x:Incident={id:"",category:String(d.get("category")),title:String(d.get("title")),location:String(d.get("location")),severity:String(d.get("severity")) as Incident["severity"],status:"À qualifier",lat:Number(d.get("latitude")),lng:Number(d.get("longitude")),color:"#d84b3e"};try{const r=await fetch("/api/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:x.title,category:x.category,location:x.location,observations:String(d.get("observations")),severity:x.severity,latitude:x.lat,longitude:x.lng})});const payload=await r.json();if(!r.ok){setFormError(payload.error||"Enregistrement impossible");return}x.id=payload.incident.reference;setItems(v=>[x,...v]);setSelected(x);setModal(false)}catch{setFormError("Connexion au serveur impossible")}}
 return <main className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><span>FER</span><i/></div><div><strong>FER SIG</strong><small>Pilotage routier</small></div></div><nav><p>PILOTAGE</p>{nav.map(([label,Icon])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><Icon size={18}/>{label}{label==="Signalements"&&<em>{items.length}</em>}</button>)}<p>ADMINISTRATION</p><button><Wrench size={18}/>Équipes & prestataires</button><button><Settings size={18}/>Paramètres</button></nav><div className="side-foot"><span/><div><strong>Système opérationnel</strong><small>Synchronisé à l’instant</small></div></div></aside>
  <section className="workspace"><header className="topbar"><button className="mobile"><Menu/></button><div><p>Plateforme de pilotage</p><h1>{active}</h1></div><div className="top-actions"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Route, ouvrage, décompte…"/></label><button className="icon"><Bell size={19}/><i/></button><div className="profile"><span>AK</span><div><strong>Amadou Koné</strong><small>Direction générale</small></div><ChevronDown size={15}/></div></div></header>
   <div className="content"><section className="heading"><div><p>Jeudi 13 août 2026</p><h2>État du réseau et des financements</h2><span>Du signalement au paiement, une vision consolidée de l’entretien routier.</span></div><div><button className="secondary"><Download size={17}/>Rapport mensuel</button><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/>Nouveau signalement</button></div></section>
    <section className="objectives"><span>OBJECTIFS FER</span><div><p><i className="ok"/>Engagements / budget <b>69,8%</b></p><p><i className="warn"/>Délai moyen de paiement <b>54 jours</b></p><p><i className="ok"/>Mobilisation annuelle <b>+11,2%</b></p><p><i className="ok"/>Charges de fonctionnement <b>2,7%</b></p></div></section>
    <section className="kpis"><article><span className="kicon red"><AlertTriangle/></span><div><small>Signalements ouverts</small><strong>128</strong><p><b>+12</b> cette semaine</p></div></article><article><span className="kicon amber"><Construction/></span><div><small>Interventions en cours</small><strong>42</strong><p>18 équipes mobilisées</p></div></article><article><span className="kicon green"><Landmark/></span><div><small>Ressources mobilisées</small><strong>36,4 Mds</strong><p><b>82%</b> de l’objectif</p></div></article><article><span className="kicon blue"><WalletCards/></span><div><small>Décomptes à régler</small><strong>5,8 Mds</strong><p><b>7</b> proches de 60 jours</p></div></article></section>
    <section className="main-grid"><article className="card map-card"><div className="card-head"><div><h3>Carte opérationnelle</h3><p>Réseau, travaux, feux, ouvrages et équipements</p></div><div className="map-actions"><button onClick={()=>setLayers(!layers)}><Layers3 size={16}/>Couches<ChevronDown size={14}/></button><button><Filter size={16}/>Filtres</button>{layers&&<div className="layer-menu"><label><input type="checkbox" defaultChecked/>Dégradations</label><label><input type="checkbox" defaultChecked/>Travaux</label><label><input type="checkbox" defaultChecked/>Péages & pesages</label><label><input type="checkbox" defaultChecked/>Ouvrages & bacs</label></div>}</div></div><div className="map-wrap"><MapView items={filtered} selected={selected} onSelect={x=>setSelected(x as Incident)}/><div className="legend"><span><i className="crit"/>Critique</span><span><i className="work"/>Intervention</span><span><i className="asset"/>Patrimoine</span></div></div></article>
     <article className="card alerts"><div className="card-head"><div><h3>Alertes prioritaires</h3><p>Éléments nécessitant une action</p></div><button className="link">Tout voir</button></div><div className="alert-list">{filtered.slice(0,4).map(x=><button key={x.id} className={selected?.id===x.id?"selected":""} onClick={()=>setSelected(x)}><span className="alert-icon" style={{background:`${x.color}18`,color:x.color}}><MapPin size={18}/></span><span className="alert-copy"><strong>{x.title}</strong><small>{x.location}</small><em>{x.id} · {x.status}</em></span><b className={`severity s-${x.severity[0]}`}>{x.severity}</b></button>)}</div></article></section>
    <section className="bottom-grid"><article className="card performance"><div className="card-head"><div><h3>Performance des travaux</h3><p>Planifié et réalisé — 30 derniers jours</p></div><select><option>30 derniers jours</option><option>Ce trimestre</option></select></div><div className="chart"><div className="y"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="bars">{[[72,84,"Nids-de-poule"],[56,68,"Débroussaillage"],[45,61,"Feux"],[63,76,"Ouvrages"],[36,54,"Bacs"]].map(([a,b,l])=><div className="bar" key={String(l)}><div><i style={{height:`${a}%`}}/><i style={{height:`${b}%`}}/></div><span>{l}</span></div>)}</div></div><div className="chart-legend"><span><i/>Planifié</span><span><i/>Réalisé</span></div></article>
     <article className="card finance"><div className="card-head"><div><h3>Maîtrise financière</h3><p>Budget d’entretien 2026</p></div><button className="link">Détails</button></div><div className="donut-row"><div className="donut"><strong>69,8%</strong><span>engagé</span></div><div className="finance-data"><p><span>Budget</span><b>21,2 Mds</b></p><p><span>Engagé</span><b>14,8 Mds</b></p><p><span>Payé</span><b>9,0 Mds</b></p><progress value="70" max="100"/></div></div><div className="payment-alert"><TrafficCone size={18}/><div><strong>7 décomptes à surveiller</strong><span>Échéance réglementaire sous 10 jours</span></div><ChevronDown/></div></article></section>
   </div>
  </section>
  {modal&&<div className="modal-bg" onMouseDown={()=>setModal(false)}><form className="modal" onSubmit={submit} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h3>Nouveau signalement</h3><p>Enregistrer une dégradation géolocalisée</p></div><button type="button" onClick={()=>setModal(false)}><X/></button></div>{formError&&<div className="login-error">{formError}</div>}<label>Intitulé<input name="title" required maxLength={160} placeholder="Ex. Nid-de-poule important"/></label><div className="form-row"><label>Catégorie<select name="category"><option>Voirie</option><option>Feux</option><option>Accotement</option><option>Ouvrage</option><option>Bac</option><option>Péage / pesage</option></select></label><label>Priorité<select name="severity"><option>Critique</option><option>Élevée</option><option>Modérée</option></select></label></div><label>Localisation<input name="location" required maxLength={240} placeholder="Route, commune ou point de repère"/></label><div className="form-row"><label>Latitude<input name="latitude" type="number" step="any" min="-90" max="90" required defaultValue="5.348"/></label><label>Longitude<input name="longitude" type="number" step="any" min="-180" max="180" required defaultValue="-4.006"/></label></div><label>Observations<textarea name="observations" maxLength={2000} placeholder="Décrivez la dégradation et les risques…"/></label><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setModal(false)}>Annuler</button><button className="primary">Enregistrer</button></div></form></div>}
 </main>
}
